---
- name: Install mongodb
  hosts: myhost
  remote_user: ubuntu
  become: true
  become_user: root
  tasks:
    - name: Install aptitude using apt
      apt:
        name: aptitude
        state: latest
        update_cache: yes

    - name: Import public key
      apt_key:
        url: 'https://www.mongodb.org/static/pgp/server-4.4.asc'
        state: present

    - name: Add repository
      apt_repository:
        filename: '/etc/apt/sources.list.d/mongodb-org-4.4.list'
        repo: 'deb https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse'
        state: present
        update_cache: yes

    - name: Install mongoDB
      apt:
        name: mongodb-org
        state: present
        update_cache: yes
- name: Install node.js, npm and python
  hosts: myhost
  remote_user: ubuntu
  become: true
  become_user: root
  tasks:
    - name: Add nodejs apt key
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
    - name: Add nodejs 14.x ppa for apt repo
      apt_repository:
        repo: deb https://deb.nodesource.com/node_14.x bionic main
    - name: Install nodejs
      apt:
        update_cache: yes
        name: nodejs
        state: latest
    - name: Install npm
      apt:
        update_cache: yes
        name: npm
        state: present
    - name: Install python3-pip
      apt:
        update_cache: yes
        name: python3-pip
        state: present
    - name: Install python3-pip
      apt:
        update_cache: yes
        name: python3-dev
        state: present
- name: Configure server
  hosts: myhost
  remote_user: ubuntu
  become: true
  become_user: root
  tasks:
    - name: Clone let's chat github
      git:
        repo: https://github.com/sdelements/lets-chat.git
        dest: /home/ubuntu/lets-chat/
        clone: yes
        update: yes
    - name: Install npm packages
      ansible.builtin.command:
        chdir: /home/ubuntu/lets-chat/
        cmd: npm install
